In [13]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [41]:
a_38 = np.array([0,1,2,3,4])
print(a_38)
a_38.ndim
a_38.shape

[0 1 2 3 4]


(5,)

In [43]:
b_38 = np.array([[[1,2,3,4],[6,7,8,9]],
             [[9,8,7,6],[5,4,3,2]],
             [[3,2,1,5],[7,5,4,9]]])
print(b_38)
b_38.ndim
b_38.shape

[[[1 2 3 4]
  [6 7 8 9]]

 [[9 8 7 6]
  [5 4 3 2]]

 [[3 2 1 5]
  [7 5 4 9]]]


(3, 2, 4)

In [37]:
c_38 = np.array([[1,2,3,4],[6,7,8,9]])
print(c_38)
c_38.shape
c_38.ndim

[[1 2 3 4]
 [6 7 8 9]]


2

(3, 2, 4)

In [51]:
a_38 = np.array([0,1,2,3,4])
print(a)

a_38[1:2]

[0 1 2 3 4]


array([1])

In [53]:
b_38 = np.array([[1,2,3,4],[6,7,8,9],[9,8,7,6]])
print(b_38)

[[1 2 3 4]
 [6 7 8 9]
 [9 8 7 6]]


In [55]:
b_38[0,1]

2

In [61]:
np.ones(0)


array([], dtype=float64)

In [63]:
print(np.ones((2,3)))
np.zeros((4,5))
print ("")
np.identity(4)

[[1. 1. 1.]
 [1. 1. 1.]]



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [67]:
np.random.rand(8,2)

array([[0.21488902, 0.14047864],
       [0.22511563, 0.54854168],
       [0.55838718, 0.83769761],
       [0.59182055, 0.86330652],
       [0.54811522, 0.07671058],
       [0.71046306, 0.65945975],
       [0.45165093, 0.93304032],
       [0.58296673, 0.3147582 ]])

In [138]:
np.random.randint(1,10,size=(3,4))

array([[1, 6, 3, 9],
       [3, 1, 2, 6],
       [8, 8, 9, 9]])

In [12]:
a_38 = np.zeros((10,10))
print(a_38)
b_38 = np.identity(10)
print(b_38)
c_38 = 9*b_38
d_38 = np.ones((8,8))
e_38 = np.identity(8)*8
f_38 = d_38+e_38
print(f_38)
c_38[1:-1,1:-1] = f_38
print(c_38)
g_38 = np.identity(6)*9
c_38[2:-2,2:-2] = g_38
print(c_38)
h_38=np.ones((4,4))*2
i_38 = np.identity(4)*7
j_38 = h_38+i_38
print(j_38)
c_38[3:-3,3:-3] = j_38
print(c_38)
k_38 = np.identity(2)*9
c_38[4:-4,4:-4] = k_38
print(c_38)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]
[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1.

In [160]:
a_38 = np.array ([
    [1,2,3,4],
    [2,8,4,9]])
b_38 = np.array ([
    [9,7,4,5],
    [6,4,3,9]])
penjumlahan_38 = a_38 + b_38
print(penjumlahan_38)

[[10  9  7  9]
 [ 8 12  7 18]]
